login: &login
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost


development:
  database: vereteno_development
  <<: *login

test:
  database: vereteno_test
  <<: *login

production:
  database: vereteno_production
  <<: *login
